######################
# - Conky settings - #
######################

background no
update_interval .3
cpu_avg_samples 2
total_run_times 0
override_utf8_locale yes

double_buffer yes
#no_buffers yes

text_buffer_size 10240
#imlib_cache_size 0

minimum_size 950 0
maximum_width 950

gap_x 5
gap_y 50
#####################
# - Text settings - #
#####################
use_xft yes
xftfont Santana:size=8
xftalpha .8
uppercase no
alignment top_left
#############################
# - Window specifications - #
#############################
own_window yes
own_window_transparent no
own_window_type override
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
own_window_class conky-semi
own_window_argb_visual yes		#-- вкл. полупрозрачный фон
own_window_argb_value 50			#-- полупрозрачный фон
border_inner_margin 3
border_outer_margin 3
#########################
# - Graphics settings - #
#########################
draw_shades no
#default_shade_color 292421
draw_outline no
draw_borders no
stippled_borders 0
draw_graph_borders no
TEXT
${execpi 5 /home/kalex/.config/conky/horical.sh}
#${font CaviarDreams:size=20}${goto 60}${color 949494}${voffset 10}${time %l:%M %P}
#${font CaviarDreams:size=12.5}${goto 90}${color 3881C7}${voffset -20}${time %A %B %d %Y}
#${voffset 20}${goto 700}${color 3881C7}${font CaviarDreams:size=10}
#${execi 1 conkyForecast-SunsetSunriseCountdown  -t} in: ${color 949494}${execi 1 conkyForecast-SunsetSunriseCountdown -L}
#${goto 700}${color 3881C7}Current Moon Phase: ${goto 900}${color 949494}${execi 300 conkyForecast --imperial --datatype=MP}
#${execpi 1800 conkyForecast --location=USME0330 --imperial --template=$HOME/Conky/LUA/day-night.template}
