[GDisk]
type = drive
scope = drive
token = {"access_token":"ya29.A0ARrdaM-mLKm2BiX6fkYzeBorNGBZp-KJZpXfAis28JLV6OxipNv90BB-q9NYvef-oyGoBdpCJ85WiOz7neAXQuX2c8rnAVWxZF1LwhmK9VfnP7jqGbzUKfGgFBEWMKb1I_ajlkjTABzLBk_xeZBwDyTRuaex058","token_type":"Bearer","refresh_token":"1//0csjlgQ27E644CgYIARAAGAwSNwF-L9IrL5vm0I8_IadF89-FVPIPJSgdl6Kbh716KYUA_mS0mrKv08oef3coXh7uaiDnnRRu_pM","expiry":"2022-01-24T03:09:32.769697577+02:00"}
team_drive = 

[MegaDrive]
type = mega
user = akalashnic@gmail.com
pass = 6-mbimtuI1p9k4tMxmP50i6fGFsKRoNFJJ_wGnqQ

