#!/bin/sh
##

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# shellcheck disable=SC1091
source "$HOME/.config/dmscripts/config"

declare -A vim_sni
vim_sni[  snippets    ]="$HOME/.config/nvim/lua/configs/friendly-snippets"
vim_sni[clear_dmenu    ]="$HOME/.local/src/dmenu/.drun_history"

vim_sni[  aliasrc     ]="$HOME/.config/shell/aliasrc"
vim_sni[  git         ]="$HOME/.config/shell/github.function"
vim_sni[ shell         ]="$HOME/.config/shell/"
vim_sni[ latex PROGECT ]="$HOME/Documents/MANUAL/shell/arguments/arguments_logical_operation.tex"

title=$(printf '%s\n' "${!vim_sni[@]}" | sort | ${DMENU} 'DTOS Help:' "$@")
path="${vim_sni["${title}"]}"

if [ -f "$path" ]; then
  # shellcheck disable=SC2154
  $DMEDITOR "${path}"
# What to do if we just escape without choosing anything.
else
    $DMTERM lfub "${path}"
fi

  echo "Program terminated." && exit 0
