[FileDialog]
history=file:///home/kalex/.config, file:///home/kalex/.config/calibre, file:///home/kalex/Documents/TEX/letter, file:///home/kalex/.config/mytetra/data, file:///home/kalex/.config/mytetra/trash, file:///home/kalex/.config/ru.webhamster.mytetra
lastVisited=file:///home/kalex/.config/ru.webhamster.mytetra
qtVersion=5.15.5
shortcuts=file:, file:///home/kalex
sidebarWidth=82
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe7\x82\0\0\0\x4\0\0\0\x1\x1\x1\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\x4\0\0\0\x81\0\0\0\x1\0\0\0\x1\0\0\0\x81\0\0\0\x1\0\0\0\x1\0\0\0\x80\0\0\0\x1\0\0\0\x1\0\0\xe6\0\0\0\0\x1\0\0\0\x1\0\0\0\x4\0\0\0\xe6\0)
viewMode=Detail
